//! The keybinding registry — DESIGN.md §4's "single source of truth".
//!
//! Every action the TUI can perform is declared **once**, in [`BINDINGS`], with
//! its id, default keys, context, description and hint priority. Four surfaces
//! are generated from that one table:
//!
//! | surface | generated by |
//! |---|---|
//! | key dispatch | [`Keymap::lookup`] |
//! | contextual hint line | [`Keymap::hints`] |
//! | `?` cheatsheet overlay | [`Keymap::cheatsheet`] |
//! | command palette (phase 6) | [`Keymap::palette`] |
//!
//! Nothing else in the crate may match on a raw [`KeyEvent`]. That rule is what
//! stops the drift DESIGN.md calls out: a binding that exists but is undocumented,
//! or a help screen that lies because a handler moved.
//!
//! # Contexts
//!
//! A binding names one [`Context`]. Dispatch takes a *stack* of contexts, most
//! specific first, and the first context in the stack that binds the key wins.
//! This is why `Ctrl+P` can be "previous completion" with the popup open and
//! "command palette" without it, from two independent declarations and no `if`.
//!
//! # What the registry deliberately does not decide
//!
//! Two keys are ambiguous by design and are resolved one layer down, in the
//! composer:
//!
//! - `Up`/`Down` bind to history recall, and the composer falls back to
//!   line-wise cursor motion when recall does not apply (DESIGN.md §4: "history
//!   (↑ at buffer start; no chord)"). Binding them twice here would need a
//!   context that depends on the caret, which is state the registry must not
//!   read.
//! - `Esc` binds to [`Action::Escape`], a single action whose meaning is the
//!   ordered ladder in [`crate::input::esc`]. The registry declares the key; the
//!   ladder decides the step.

pub mod config;
pub mod spec;

use std::collections::HashMap;

use crate::input::key::KeyEvent;

/// Everything the key layer can ask for.
///
/// The discriminants are never serialised; [`Action::id`] is the stable name
/// that appears in `[tui.keys]`, in the palette and in help.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Action {
    // -- turn control ------------------------------------------------------
    /// Send the composer, or queue it when a turn is running (DESIGN.md §0.2).
    Submit,
    /// Flush the queue into the running turn as steering.
    Steer,
    /// Cancel the running turn, keeping partial output. Twice in a row exits.
    Cancel,
    /// Leave the application.
    Quit,
    /// The ordered Esc ladder. See [`crate::input::esc`].
    Escape,

    // -- surfaces ----------------------------------------------------------
    /// Expand the most recent tool call in the transcript.
    ExpandLastTool,
    /// Open the command palette.
    Palette,
    /// Open the `?` cheatsheet.
    Help,
    /// Accept the highlighted row of a select overlay.
    OverlayAccept,
    /// Close the topmost overlay.
    OverlayDismiss,
    /// Scroll an overlay.
    OverlayScrollUp,
    /// Scroll an overlay.
    OverlayScrollDown,
    /// Highlight the next row of a select overlay.
    OverlayNext,
    /// Highlight the previous row of a select overlay.
    OverlayPrev,
    /// Delete one character from a select overlay's filter.
    OverlayFilterDelete,
    /// Accept the selected completion.
    CompletionAccept,
    /// Select the next completion.
    CompletionNext,
    /// Select the previous completion.
    CompletionPrev,

    // -- forms -------------------------------------------------------------
    /// Move to the next field of a form.
    FormNextField,
    /// Move to the previous field of a form.
    FormPrevField,
    /// Next choice of a choice field; caret right in a text field.
    FormNextOption,
    /// Previous choice of a choice field; caret left in a text field.
    FormPrevOption,
    /// Advance to the next field, or submit the form from the last one.
    FormSubmit,
    /// Check the form's answer against the world before committing it.
    FormVerify,

    // -- composer ----------------------------------------------------------
    /// Insert a hard line break.
    Newline,
    /// Recall the previous prompt, else move the caret up a line.
    HistoryPrev,
    /// Recall the next prompt, else move the caret down a line.
    HistoryNext,
    /// Caret one grapheme left.
    MoveCharLeft,
    /// Caret one grapheme right.
    MoveCharRight,
    /// Caret one word left.
    MoveWordLeft,
    /// Caret one word right.
    MoveWordRight,
    /// Caret to the start of the visual line.
    MoveLineStart,
    /// Caret to the end of the visual line.
    MoveLineEnd,
    /// Caret to the start of the buffer.
    MoveBufferStart,
    /// Caret to the end of the buffer.
    MoveBufferEnd,
    /// Delete the grapheme before the caret.
    DeleteCharBefore,
    /// Delete the grapheme after the caret.
    DeleteCharAfter,
    /// Kill from the caret to the end of the line.
    KillToLineEnd,
    /// Kill from the start of the line to the caret.
    KillToLineStart,
    /// Kill the word before the caret.
    KillWordBefore,
    /// Kill the word after the caret.
    KillWordAfter,
    /// Yank the kill ring at the caret.
    Yank,
    /// Replace the last yank with the previous kill-ring entry.
    YankPop,
    /// Swap the two graphemes around the caret.
    TransposeChars,
    /// Undo one edit group.
    Undo,
    /// Redo one edit group.
    Redo,
    /// Repaint the screen.
    ClearScreen,
}

impl Action {
    /// The stable name used by `[tui.keys]`, the palette and help.
    #[must_use]
    pub const fn id(self) -> &'static str {
        match self {
            Self::Submit => "submit",
            Self::Steer => "steer",
            Self::Cancel => "cancel",
            Self::Quit => "quit",
            Self::Escape => "escape",
            Self::ExpandLastTool => "expand-last-tool",
            Self::Palette => "palette",
            Self::Help => "help",
            Self::OverlayAccept => "overlay-accept",
            Self::OverlayDismiss => "overlay-dismiss",
            Self::OverlayScrollUp => "overlay-scroll-up",
            Self::OverlayScrollDown => "overlay-scroll-down",
            Self::OverlayNext => "overlay-next",
            Self::OverlayPrev => "overlay-prev",
            Self::OverlayFilterDelete => "overlay-filter-delete",
            Self::CompletionAccept => "completion-accept",
            Self::CompletionNext => "completion-next",
            Self::CompletionPrev => "completion-prev",
            Self::FormNextField => "form-next-field",
            Self::FormPrevField => "form-prev-field",
            Self::FormNextOption => "form-next-option",
            Self::FormPrevOption => "form-prev-option",
            Self::FormSubmit => "form-submit",
            Self::FormVerify => "form-verify",
            Self::Newline => "newline",
            Self::HistoryPrev => "history-prev",
            Self::HistoryNext => "history-next",
            Self::MoveCharLeft => "move-char-left",
            Self::MoveCharRight => "move-char-right",
            Self::MoveWordLeft => "move-word-left",
            Self::MoveWordRight => "move-word-right",
            Self::MoveLineStart => "move-line-start",
            Self::MoveLineEnd => "move-line-end",
            Self::MoveBufferStart => "move-buffer-start",
            Self::MoveBufferEnd => "move-buffer-end",
            Self::DeleteCharBefore => "delete-char-before",
            Self::DeleteCharAfter => "delete-char-after",
            Self::KillToLineEnd => "kill-to-line-end",
            Self::KillToLineStart => "kill-to-line-start",
            Self::KillWordBefore => "kill-word-before",
            Self::KillWordAfter => "kill-word-after",
            Self::Yank => "yank",
            Self::YankPop => "yank-pop",
            Self::TransposeChars => "transpose-chars",
            Self::Undo => "undo",
            Self::Redo => "redo",
            Self::ClearScreen => "clear-screen",
        }
    }

    /// Look an action up by its stable id.
    #[must_use]
    pub fn from_id(id: &str) -> Option<Self> {
        BINDINGS
            .iter()
            .map(|binding| binding.action)
            .find(|action| action.id() == id)
    }
}

/// Where a binding applies.
///
/// Listed in the order a full stack uses them, most specific first. The order of
/// the *stack* is what decides precedence, not this declaration order, but they
/// are kept in agreement so the enum reads as the precedence it produces.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Context {
    /// A **filterable** overlay — a palette or a picker — is open.
    ///
    /// Split from [`Context::Overlay`] because a select overlay filters as you
    /// type, so every printable key belongs to its query. `q` closing a
    /// cheatsheet is a convenience; `q` closing a palette the moment you type
    /// `quit` into it is a bug. The two are therefore different contexts and the
    /// select layer simply does not stack `Overlay` underneath itself.
    OverlaySelect,
    /// A **form** overlay is open (provider setup).
    ///
    /// Its own context for the same reason [`Context::OverlaySelect`] is: every
    /// printable key belongs to the focused field, and the composer is not
    /// reachable behind it. It re-declares the readline motions rather than
    /// stacking `Composer` underneath, because `Enter`, `Tab`, `←` and `→` mean
    /// something else here and a stacked context would resolve them wrongly.
    Form,
    /// A non-filtering overlay (the cheatsheet) is open.
    Overlay,
    /// The `@`/`/` completion popup is open.
    Completion,
    /// The composer has focus and its buffer is empty.
    ComposerEmpty,
    /// The composer has focus.
    Composer,
    /// A turn is streaming or retrying.
    Streaming,
    /// Always.
    Global,
}

impl Context {
    /// Heading used by the cheatsheet.
    #[must_use]
    pub const fn title(self) -> &'static str {
        match self {
            Self::OverlaySelect => "picker",
            Self::Form => "form",
            Self::Overlay => "overlay",
            Self::Completion => "completion",
            Self::ComposerEmpty => "empty composer",
            Self::Composer => "composer",
            Self::Streaming => "while streaming",
            Self::Global => "anywhere",
        }
    }
}

/// The context stack for a dispatch, most specific first.
///
/// Built from live UI state by [`ContextStack::build`] so no other module has to
/// remember the precedence order.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct ContextStack(Vec<Context>);

/// Which overlay, if any, has the keyboard.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum Layer {
    /// No overlay.
    #[default]
    None,
    /// A non-filtering overlay: the cheatsheet.
    Overlay,
    /// A filterable overlay: the palette, a picker.
    Select,
    /// A form overlay: provider setup.
    Form,
}

impl Layer {
    /// Whether any overlay is open.
    #[must_use]
    pub const fn is_open(self) -> bool {
        !matches!(self, Self::None)
    }
}

impl ContextStack {
    /// Build the stack from the four booleans that actually vary.
    #[must_use]
    pub fn build(overlay: bool, completion: bool, composer_empty: bool, streaming: bool) -> Self {
        let layer = if overlay { Layer::Overlay } else { Layer::None };
        Self::layered(layer, completion, composer_empty, streaming)
    }

    /// As [`ContextStack::build`], naming which kind of overlay is open.
    #[must_use]
    pub fn layered(
        layer: Layer,
        completion: bool,
        composer_empty: bool,
        streaming: bool,
    ) -> Self {
        let mut stack = Vec::with_capacity(6);
        match layer {
            Layer::None => {}
            Layer::Overlay => stack.push(Context::Overlay),
            // Deliberately *not* also `Overlay`: see [`Context::OverlaySelect`].
            Layer::Select => stack.push(Context::OverlaySelect),
            // Likewise, and additionally not `Composer`: see [`Context::Form`].
            Layer::Form => stack.push(Context::Form),
        }
        if completion {
            stack.push(Context::Completion);
        }
        // An overlay takes the keyboard: the composer is not reachable behind it.
        if !layer.is_open() {
            if composer_empty {
                stack.push(Context::ComposerEmpty);
            }
            stack.push(Context::Composer);
        }
        if streaming {
            stack.push(Context::Streaming);
        }
        stack.push(Context::Global);
        Self(stack)
    }

    /// The contexts, most specific first.
    #[must_use]
    pub fn contexts(&self) -> &[Context] {
        &self.0
    }
}

/// Hint priority. Higher is shown first; `0` never appears in the hint line.
pub type HintPriority = u8;

/// One declaration.
#[derive(Debug, Clone, Copy)]
pub struct Binding {
    /// The action it invokes.
    pub action: Action,
    /// Where it applies.
    pub context: Context,
    /// Default key specs, most canonical first. The first is the one help shows.
    pub keys: &'static [&'static str],
    /// Verb for the one-line hint bar. Empty means "never in the hint bar".
    pub short: &'static str,
    /// Prose for the cheatsheet and the palette.
    pub description: &'static str,
    /// Hint-bar priority.
    pub hint: HintPriority,
}

/// Every binding in the TUI.
///
/// DESIGN.md §4's set is here in full: `Enter` submit/queue, `Ctrl+S`
/// steer-flush, the `Esc` family, `Ctrl+C` cancel/exit, `Tab` expand-last-tool,
/// `Ctrl+P` palette, history `↑`/`↓`, and the readline/emacs set.
pub const BINDINGS: &[Binding] = &[
    // -- composer: the four keys a user actually looks for ------------------
    Binding {
        action: Action::Submit,
        context: Context::Composer,
        keys: &["enter"],
        short: "send",
        description: "Send the prompt. While a turn is running it queues instead.",
        hint: 100,
    },
    Binding {
        action: Action::Steer,
        context: Context::Streaming,
        keys: &["ctrl+s"],
        short: "steer now",
        description: "Flush the queue into the running turn as a steering message.",
        hint: 95,
    },
    Binding {
        action: Action::Escape,
        context: Context::Global,
        keys: &["esc"],
        short: "back",
        description: "Dismiss overlay → clear composer → unqueue → cancel turn → rewind.",
        hint: 90,
    },
    Binding {
        action: Action::Cancel,
        context: Context::Global,
        keys: &["ctrl+c"],
        short: "cancel",
        description: "Cancel the running turn, keeping partial output. Twice in a row exits.",
        hint: 70,
    },
    Binding {
        action: Action::Newline,
        context: Context::Composer,
        // Order matters: the first spec is what help prints. `shift+enter` needs
        // the kitty protocol; `alt+enter` is the universal fallback and `ctrl+j`
        // works even on a terminal that eats Alt.
        keys: &["shift+enter", "alt+enter", "ctrl+j"],
        short: "newline",
        description: "Insert a line break without sending.",
        hint: 60,
    },
    Binding {
        action: Action::ExpandLastTool,
        context: Context::Global,
        keys: &["tab"],
        short: "expand",
        description: "Expand the most recent tool call.",
        hint: 50,
    },
    Binding {
        action: Action::Palette,
        context: Context::Global,
        keys: &["ctrl+p"],
        short: "palette",
        description: "Open the command palette.",
        hint: 40,
    },
    Binding {
        action: Action::Help,
        context: Context::ComposerEmpty,
        keys: &["?"],
        short: "help",
        description: "Show the key cheatsheet.",
        hint: 30,
    },
    Binding {
        action: Action::Quit,
        context: Context::ComposerEmpty,
        keys: &["ctrl+d"],
        short: "",
        description: "Exit, when the composer is empty.",
        hint: 0,
    },
    // -- history -----------------------------------------------------------
    Binding {
        action: Action::HistoryPrev,
        context: Context::Composer,
        keys: &["up"],
        short: "history",
        description: "Previous prompt. Only recalls from the start of the buffer; \
                      otherwise moves the caret up a line.",
        hint: 20,
    },
    Binding {
        action: Action::HistoryNext,
        context: Context::Composer,
        keys: &["down"],
        short: "",
        description: "Next prompt, or move the caret down a line.",
        hint: 0,
    },
    // -- overlays ----------------------------------------------------------
    Binding {
        action: Action::OverlayDismiss,
        context: Context::Overlay,
        keys: &["q"],
        short: "close",
        description: "Close the overlay.",
        hint: 80,
    },
    Binding {
        action: Action::OverlayScrollUp,
        context: Context::Overlay,
        keys: &["up", "ctrl+p"],
        short: "",
        description: "Scroll up.",
        hint: 0,
    },
    Binding {
        action: Action::OverlayScrollDown,
        context: Context::Overlay,
        keys: &["down", "ctrl+n"],
        short: "",
        description: "Scroll down.",
        hint: 0,
    },
    // -- pickers -----------------------------------------------------------
    // No `q` here on purpose: every printable key belongs to the filter, and
    // `Esc` (global, rung 1 of the ladder) is how a picker closes.
    Binding {
        action: Action::OverlayAccept,
        context: Context::OverlaySelect,
        keys: &["enter", "tab"],
        short: "choose",
        description: "Run, or switch to, the highlighted entry.",
        hint: 85,
    },
    Binding {
        action: Action::OverlayNext,
        context: Context::OverlaySelect,
        keys: &["down", "ctrl+n"],
        short: "",
        description: "Highlight the next entry.",
        hint: 0,
    },
    Binding {
        action: Action::OverlayPrev,
        context: Context::OverlaySelect,
        keys: &["up", "ctrl+p"],
        short: "",
        description: "Highlight the previous entry.",
        hint: 0,
    },
    Binding {
        action: Action::OverlayFilterDelete,
        context: Context::OverlaySelect,
        keys: &["backspace"],
        short: "",
        description: "Delete a character from the filter.",
        hint: 0,
    },
    // -- forms -------------------------------------------------------------
    // A form re-declares the editing keys instead of stacking `Composer`
    // underneath: `enter`, `tab`, `←` and `→` all mean something else here, and
    // a stacked context would resolve them to the composer's meaning first.
    Binding {
        action: Action::FormSubmit,
        context: Context::Form,
        keys: &["enter"],
        short: "next / save",
        description: "Move to the next field; from the last one, save the form.",
        hint: 100,
    },
    Binding {
        action: Action::FormNextField,
        context: Context::Form,
        keys: &["tab", "down"],
        short: "",
        description: "Next field.",
        hint: 0,
    },
    Binding {
        action: Action::FormPrevField,
        context: Context::Form,
        keys: &["shift+tab", "up"],
        short: "back",
        description: "Previous field.",
        hint: 55,
    },
    Binding {
        action: Action::FormNextOption,
        context: Context::Form,
        keys: &["right", "ctrl+n"],
        short: "choose",
        description: "Next choice, or the caret one character right in a text field.",
        hint: 50,
    },
    Binding {
        action: Action::FormPrevOption,
        context: Context::Form,
        keys: &["left", "ctrl+p"],
        short: "",
        description: "Previous choice, or the caret one character left in a text field.",
        hint: 0,
    },
    Binding {
        action: Action::FormVerify,
        context: Context::Form,
        keys: &["ctrl+t"],
        short: "check",
        description: "Try the endpoint before saving it. Optional, and never blocking.",
        hint: 65,
    },
    Binding {
        action: Action::DeleteCharBefore,
        context: Context::Form,
        keys: &["backspace"],
        short: "",
        description: "Delete backwards.",
        hint: 0,
    },
    Binding {
        action: Action::DeleteCharAfter,
        context: Context::Form,
        keys: &["delete"],
        short: "",
        description: "Delete forwards.",
        hint: 0,
    },
    Binding {
        action: Action::MoveCharLeft,
        context: Context::Form,
        keys: &["ctrl+b"],
        short: "",
        description: "Back one character.",
        hint: 0,
    },
    Binding {
        action: Action::MoveCharRight,
        context: Context::Form,
        keys: &["ctrl+f"],
        short: "",
        description: "Forward one character.",
        hint: 0,
    },
    Binding {
        action: Action::MoveWordLeft,
        context: Context::Form,
        keys: &["alt+b", "alt+left"],
        short: "",
        description: "Back one word.",
        hint: 0,
    },
    Binding {
        action: Action::MoveWordRight,
        context: Context::Form,
        keys: &["alt+f", "alt+right"],
        short: "",
        description: "Forward one word.",
        hint: 0,
    },
    Binding {
        action: Action::MoveLineStart,
        context: Context::Form,
        keys: &["ctrl+a", "home"],
        short: "",
        description: "Beginning of the field.",
        hint: 0,
    },
    Binding {
        action: Action::MoveLineEnd,
        context: Context::Form,
        keys: &["ctrl+e", "end"],
        short: "",
        description: "End of the field.",
        hint: 0,
    },
    Binding {
        action: Action::KillWordBefore,
        context: Context::Form,
        keys: &["ctrl+w", "alt+backspace"],
        short: "",
        description: "Kill the previous word.",
        hint: 0,
    },
    Binding {
        action: Action::KillToLineStart,
        context: Context::Form,
        keys: &["ctrl+u"],
        short: "",
        description: "Clear the field up to the caret.",
        hint: 0,
    },
    Binding {
        action: Action::KillToLineEnd,
        context: Context::Form,
        keys: &["ctrl+k"],
        short: "",
        description: "Clear the field from the caret.",
        hint: 0,
    },
    // -- completion --------------------------------------------------------
    Binding {
        action: Action::CompletionAccept,
        context: Context::Completion,
        keys: &["tab", "enter"],
        short: "accept",
        description: "Accept the selected completion.",
        hint: 85,
    },
    Binding {
        action: Action::CompletionNext,
        context: Context::Completion,
        keys: &["down", "ctrl+n"],
        short: "",
        description: "Next candidate.",
        hint: 0,
    },
    Binding {
        action: Action::CompletionPrev,
        context: Context::Completion,
        keys: &["up", "ctrl+p"],
        short: "",
        description: "Previous candidate.",
        hint: 0,
    },
    // -- readline / emacs set ----------------------------------------------
    Binding {
        action: Action::MoveLineStart,
        context: Context::Composer,
        keys: &["ctrl+a", "home"],
        short: "",
        description: "Beginning of line.",
        hint: 0,
    },
    Binding {
        action: Action::MoveLineEnd,
        context: Context::Composer,
        keys: &["ctrl+e", "end"],
        short: "",
        description: "End of line.",
        hint: 0,
    },
    Binding {
        action: Action::MoveCharLeft,
        context: Context::Composer,
        keys: &["ctrl+b", "left"],
        short: "",
        description: "Back one character.",
        hint: 0,
    },
    Binding {
        action: Action::MoveCharRight,
        context: Context::Composer,
        keys: &["ctrl+f", "right"],
        short: "",
        description: "Forward one character.",
        hint: 0,
    },
    Binding {
        action: Action::MoveWordLeft,
        context: Context::Composer,
        keys: &["alt+b", "ctrl+left", "alt+left"],
        short: "",
        description: "Back one word.",
        hint: 0,
    },
    Binding {
        action: Action::MoveWordRight,
        context: Context::Composer,
        keys: &["alt+f", "ctrl+right", "alt+right"],
        short: "",
        description: "Forward one word.",
        hint: 0,
    },
    Binding {
        action: Action::MoveBufferStart,
        context: Context::Composer,
        keys: &["alt+<", "ctrl+home"],
        short: "",
        description: "Beginning of the buffer.",
        hint: 0,
    },
    Binding {
        action: Action::MoveBufferEnd,
        context: Context::Composer,
        keys: &["alt+>", "ctrl+end"],
        short: "",
        description: "End of the buffer.",
        hint: 0,
    },
    Binding {
        action: Action::DeleteCharBefore,
        context: Context::Composer,
        keys: &["backspace"],
        short: "",
        description: "Delete backwards. Removes a whole paste chip at once.",
        hint: 0,
    },
    Binding {
        action: Action::DeleteCharAfter,
        context: Context::Composer,
        keys: &["ctrl+d", "delete"],
        short: "",
        description: "Delete forwards.",
        hint: 0,
    },
    Binding {
        action: Action::KillToLineEnd,
        context: Context::Composer,
        keys: &["ctrl+k"],
        short: "",
        description: "Kill to end of line (appends to the kill ring).",
        hint: 0,
    },
    Binding {
        action: Action::KillToLineStart,
        context: Context::Composer,
        keys: &["ctrl+u"],
        short: "",
        description: "Kill to start of line (prepends to the kill ring).",
        hint: 0,
    },
    Binding {
        action: Action::KillWordBefore,
        context: Context::Composer,
        keys: &["ctrl+w", "alt+backspace"],
        short: "",
        description: "Kill the previous word.",
        hint: 0,
    },
    Binding {
        action: Action::KillWordAfter,
        context: Context::Composer,
        keys: &["alt+d"],
        short: "",
        description: "Kill the next word.",
        hint: 0,
    },
    Binding {
        action: Action::Yank,
        context: Context::Composer,
        keys: &["ctrl+y"],
        short: "",
        description: "Yank the kill ring.",
        hint: 0,
    },
    Binding {
        action: Action::YankPop,
        context: Context::Composer,
        keys: &["alt+y"],
        short: "",
        description: "Cycle the yanked text through older kill-ring entries.",
        hint: 0,
    },
    Binding {
        action: Action::TransposeChars,
        context: Context::Composer,
        keys: &["ctrl+t"],
        short: "",
        description: "Transpose the characters around the caret.",
        hint: 0,
    },
    Binding {
        action: Action::Undo,
        context: Context::Composer,
        keys: &["ctrl+z", "ctrl+_"],
        short: "",
        description: "Undo one edit group.",
        hint: 0,
    },
    Binding {
        action: Action::Redo,
        context: Context::Composer,
        keys: &["alt+z"],
        short: "",
        description: "Redo one edit group.",
        hint: 0,
    },
    Binding {
        action: Action::ClearScreen,
        context: Context::Global,
        keys: &["ctrl+l"],
        short: "",
        description: "Repaint the screen.",
        hint: 0,
    },
];

/// A resolved binding: default keys, plus whatever `[tui.keys]` said.
#[derive(Debug, Clone)]
pub struct Resolved {
    /// The declaration.
    pub binding: Binding,
    /// Keys in effect. Empty when the user unbound the action with `false`.
    pub keys: Vec<KeyEvent>,
}

/// One row of the hint bar or the cheatsheet.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Hint {
    /// The action, so a caller can relabel it (the Esc ladder does).
    pub action: Action,
    /// Canonical key spelling, e.g. `ctrl+s`.
    pub key: String,
    /// Hint verb.
    pub short: &'static str,
    /// Priority, for width-starved degradation.
    pub priority: HintPriority,
}

/// The resolved keymap.
#[derive(Debug, Clone)]
pub struct Keymap {
    resolved: Vec<Resolved>,
    lookup: HashMap<Context, HashMap<KeyEvent, Action>>,
    warnings: Vec<String>,
}

impl Default for Keymap {
    fn default() -> Self {
        Self::new(&config::KeyOverrides::default())
    }
}

impl Keymap {
    /// Build the keymap from [`BINDINGS`] and a user override table.
    #[must_use]
    pub fn new(overrides: &config::KeyOverrides) -> Self {
        let mut resolved = Vec::with_capacity(BINDINGS.len());
        let mut warnings = overrides.warnings().to_vec();
        for binding in BINDINGS {
            let keys = match overrides.get(binding.action) {
                Some(config::Override::Unbind) => Vec::new(),
                Some(config::Override::Keys(keys)) => keys.clone(),
                None => binding
                    .keys
                    .iter()
                    .filter_map(|spec| match spec::parse_key(spec) {
                        Ok(key) => Some(key),
                        Err(error) => {
                            // A malformed *default* is a bug in this file, not in
                            // a user's config; surface it loudly in debug builds.
                            debug_assert!(false, "default binding {spec:?}: {error}");
                            None
                        }
                    })
                    .collect(),
            };
            resolved.push(Resolved {
                binding: *binding,
                keys,
            });
        }

        let mut lookup: HashMap<Context, HashMap<KeyEvent, Action>> = HashMap::new();
        for entry in &resolved {
            let context = lookup.entry(entry.binding.context).or_default();
            for key in &entry.keys {
                if let Some(previous) = context
                    .insert(*key, entry.binding.action)
                    .filter(|previous| *previous != entry.binding.action)
                {
                    warnings.push(format!(
                        "{key} is bound to both `{}` and `{}` in {}; \
                         the later declaration wins",
                        previous.id(),
                        entry.binding.action.id(),
                        entry.binding.context.title()
                    ));
                }
            }
        }
        Self {
            resolved,
            lookup,
            warnings,
        }
    }

    /// Diagnostics from building the map: bad specs, unknown ids, conflicts.
    ///
    /// Never fatal. A broken `[tui.keys]` entry costs its own binding and
    /// nothing else.
    #[must_use]
    pub fn warnings(&self) -> &[String] {
        &self.warnings
    }

    /// Resolve a key against a context stack.
    ///
    /// The first context in the stack that binds the key wins; there is no
    /// fall-through *within* a context.
    #[must_use]
    pub fn lookup(&self, key: KeyEvent, stack: &ContextStack) -> Option<Action> {
        stack
            .contexts()
            .iter()
            .find_map(|context| self.lookup.get(context)?.get(&key).copied())
    }

    /// The keys currently bound to an action, canonical spelling first.
    #[must_use]
    pub fn keys_for(&self, action: Action) -> Vec<KeyEvent> {
        self.resolved
            .iter()
            .filter(|entry| entry.binding.action == action)
            .flat_map(|entry| entry.keys.iter().copied())
            .collect()
    }

    /// The hint bar for a context stack: every visible binding reachable from
    /// the stack, highest priority first.
    ///
    /// Shadowed bindings are omitted — a hint that names a key the user cannot
    /// press right now is worse than no hint.
    #[must_use]
    pub fn hints(&self, stack: &ContextStack) -> Vec<Hint> {
        let mut hints: Vec<Hint> = Vec::new();
        for context in stack.contexts() {
            for entry in self
                .resolved
                .iter()
                .filter(|entry| entry.binding.context == *context)
            {
                if entry.binding.hint == 0 || entry.binding.short.is_empty() {
                    continue;
                }
                let Some(key) = entry.keys.first() else {
                    continue;
                };
                // Shadowed by a more specific context earlier in the stack.
                if self.lookup(*key, stack) != Some(entry.binding.action) {
                    continue;
                }
                if hints.iter().any(|hint| hint.action == entry.binding.action) {
                    continue;
                }
                hints.push(Hint {
                    action: entry.binding.action,
                    key: key.to_string(),
                    short: entry.binding.short,
                    priority: entry.binding.hint,
                });
            }
        }
        hints.sort_by(|a, b| b.priority.cmp(&a.priority).then(a.key.cmp(&b.key)));
        hints
    }

    /// The `?` cheatsheet: every bound action, grouped by context in the
    /// declaration order of [`Context`].
    #[must_use]
    pub fn cheatsheet(&self) -> Vec<(Context, Vec<CheatEntry>)> {
        let mut groups: Vec<(Context, Vec<CheatEntry>)> = Vec::new();
        for context in [
            Context::Global,
            Context::Composer,
            Context::ComposerEmpty,
            Context::Streaming,
            Context::Completion,
            Context::Overlay,
            Context::OverlaySelect,
            Context::Form,
        ] {
            let entries: Vec<CheatEntry> = self
                .resolved
                .iter()
                .filter(|entry| entry.binding.context == context && !entry.keys.is_empty())
                .map(|entry| CheatEntry {
                    action: entry.binding.action,
                    context,
                    keys: entry
                        .keys
                        .iter()
                        .map(ToString::to_string)
                        .collect::<Vec<_>>()
                        .join(" / "),
                    description: entry.binding.description,
                })
                .collect();
            if !entries.is_empty() {
                groups.push((context, entries));
            }
        }
        groups
    }

    /// Palette rows: id, key hint and description for every action.
    ///
    /// Phase 6 wires this to `Ctrl+P` and to `/name`; it exists now so the one
    /// declaration already serves all three surfaces.
    #[must_use]
    pub fn palette(&self) -> Vec<CheatEntry> {
        let mut rows: Vec<CheatEntry> = self
            .resolved
            .iter()
            .map(|entry| CheatEntry {
                action: entry.binding.action,
                context: entry.binding.context,
                keys: entry
                    .keys
                    .first()
                    .map(ToString::to_string)
                    .unwrap_or_default(),
                description: entry.binding.description,
            })
            .collect();
        rows.sort_by_key(|row| row.action.id());
        rows
    }
}

/// One row of the cheatsheet or the palette.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CheatEntry {
    /// The action.
    pub action: Action,
    /// Where the binding applies. The palette uses it to leave out actions that
    /// only exist *inside* a surface the palette itself would close.
    pub context: Context,
    /// Key spellings, `/`-separated.
    pub keys: String,
    /// Prose.
    pub description: &'static str,
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::input::key::{KeyCode, KeyMods};

    fn key(spec: &str) -> KeyEvent {
        spec::parse_key(spec).unwrap()
    }

    #[test]
    fn every_default_spec_parses() {
        for binding in BINDINGS {
            for name in binding.keys {
                assert!(
                    spec::parse_key(name).is_ok(),
                    "{} declares an unparseable key {name:?}",
                    binding.action.id()
                );
            }
        }
    }

    #[test]
    fn action_ids_are_unique_per_context_and_round_trip() {
        // Per *context*, not globally: an editing action is deliberately
        // declared twice, once for the composer and once for a form, because
        // the two surfaces reach it with different keys. Two declarations of
        // the same action in the *same* context would still be a bug — the
        // second silently wins the lookup table.
        let mut seen = std::collections::HashSet::new();
        for binding in BINDINGS {
            let id = binding.action.id();
            assert_eq!(Action::from_id(id), Some(binding.action));
            assert!(
                seen.insert((binding.context, id)),
                "duplicate declaration for {id} in {}",
                binding.context.title()
            );
        }
    }

    #[test]
    fn a_form_reaches_the_composers_editor_without_reaching_its_enter() {
        let keymap = Keymap::default();
        let form = ContextStack::layered(Layer::Form, false, false, false);
        // The editing set is the composer's, by the same action ids.
        assert_eq!(
            keymap.lookup(key("ctrl+w"), &form),
            Some(Action::KillWordBefore)
        );
        assert_eq!(keymap.lookup(key("alt+b"), &form), Some(Action::MoveWordLeft));
        assert_eq!(
            keymap.lookup(key("backspace"), &form),
            Some(Action::DeleteCharBefore)
        );
        // The four keys that mean something else here do mean something else.
        assert_eq!(keymap.lookup(key("enter"), &form), Some(Action::FormSubmit));
        assert_eq!(keymap.lookup(key("tab"), &form), Some(Action::FormNextField));
        assert_eq!(
            keymap.lookup(key("shift+tab"), &form),
            Some(Action::FormPrevField)
        );
        assert_eq!(
            keymap.lookup(key("right"), &form),
            Some(Action::FormNextOption)
        );
        assert_eq!(keymap.lookup(key("ctrl+t"), &form), Some(Action::FormVerify));
        // And the composer is not reachable behind the form.
        assert!(
            !form.contexts().contains(&Context::Composer),
            "{:?}",
            form.contexts()
        );
        // `Esc` stays the global ladder: rung 1 dismisses the overlay.
        assert_eq!(keymap.lookup(key("esc"), &form), Some(Action::Escape));
    }

    #[test]
    fn the_form_hint_line_never_names_a_key_the_form_does_not_answer() {
        let keymap = Keymap::default();
        let form = ContextStack::layered(Layer::Form, false, false, false);
        for hint in keymap.hints(&form) {
            let key = spec::parse_key(&hint.key).expect("a canonical spelling");
            assert_eq!(
                keymap.lookup(key, &form),
                Some(hint.action),
                "{} is hinted but resolves elsewhere",
                hint.key
            );
        }
    }

    #[test]
    fn the_default_map_has_no_conflicts() {
        let keymap = Keymap::default();
        assert_eq!(keymap.warnings(), &[] as &[String], "{:?}", keymap.warnings());
    }

    #[test]
    fn the_design_bindings_resolve_from_a_plain_composer() {
        let keymap = Keymap::default();
        let stack = ContextStack::build(false, false, false, false);
        assert_eq!(keymap.lookup(key("enter"), &stack), Some(Action::Submit));
        assert_eq!(keymap.lookup(key("esc"), &stack), Some(Action::Escape));
        assert_eq!(keymap.lookup(key("ctrl+c"), &stack), Some(Action::Cancel));
        assert_eq!(
            keymap.lookup(key("tab"), &stack),
            Some(Action::ExpandLastTool)
        );
        assert_eq!(keymap.lookup(key("ctrl+p"), &stack), Some(Action::Palette));
        assert_eq!(keymap.lookup(key("up"), &stack), Some(Action::HistoryPrev));
        assert_eq!(
            keymap.lookup(key("ctrl+a"), &stack),
            Some(Action::MoveLineStart)
        );
        assert_eq!(keymap.lookup(key("alt+b"), &stack), Some(Action::MoveWordLeft));
        assert_eq!(keymap.lookup(key("ctrl+y"), &stack), Some(Action::Yank));
    }

    #[test]
    fn steer_is_reachable_only_while_streaming() {
        let keymap = Keymap::default();
        let idle = ContextStack::build(false, false, false, false);
        let streaming = ContextStack::build(false, false, false, true);
        assert_eq!(keymap.lookup(key("ctrl+s"), &idle), None);
        assert_eq!(keymap.lookup(key("ctrl+s"), &streaming), Some(Action::Steer));
    }

    #[test]
    fn all_three_newline_spellings_reach_the_same_action() {
        let keymap = Keymap::default();
        let stack = ContextStack::build(false, false, false, false);
        for spec in ["shift+enter", "alt+enter", "ctrl+j"] {
            assert_eq!(
                keymap.lookup(key(spec), &stack),
                Some(Action::Newline),
                "{spec}"
            );
        }
    }

    #[test]
    fn a_more_specific_context_shadows_a_general_one() {
        let keymap = Keymap::default();
        let plain = ContextStack::build(false, false, false, false);
        let completing = ContextStack::build(false, true, false, false);
        assert_eq!(keymap.lookup(key("tab"), &plain), Some(Action::ExpandLastTool));
        assert_eq!(
            keymap.lookup(key("tab"), &completing),
            Some(Action::CompletionAccept),
            "the popup owns Tab while it is open"
        );
        assert_eq!(keymap.lookup(key("ctrl+p"), &plain), Some(Action::Palette));
        assert_eq!(
            keymap.lookup(key("ctrl+p"), &completing),
            Some(Action::CompletionPrev)
        );
    }

    #[test]
    fn ctrl_d_deletes_forward_but_exits_from_an_empty_composer() {
        let keymap = Keymap::default();
        let typing = ContextStack::build(false, false, false, false);
        let empty = ContextStack::build(false, false, true, false);
        assert_eq!(
            keymap.lookup(key("ctrl+d"), &typing),
            Some(Action::DeleteCharAfter)
        );
        assert_eq!(keymap.lookup(key("ctrl+d"), &empty), Some(Action::Quit));
    }

    #[test]
    fn help_is_only_bound_where_question_mark_is_not_text() {
        let keymap = Keymap::default();
        assert_eq!(
            keymap.lookup(key("?"), &ContextStack::build(false, false, true, false)),
            Some(Action::Help)
        );
        assert_eq!(
            keymap.lookup(key("?"), &ContextStack::build(false, false, false, false)),
            None,
            "typing `?` mid-sentence must insert a question mark"
        );
    }

    #[test]
    fn an_overlay_takes_the_keyboard_away_from_the_composer() {
        let keymap = Keymap::default();
        let stack = ContextStack::build(true, false, true, false);
        assert_eq!(keymap.lookup(key("enter"), &stack), None);
        assert_eq!(keymap.lookup(key("q"), &stack), Some(Action::OverlayDismiss));
        assert_eq!(keymap.lookup(key("esc"), &stack), Some(Action::Escape));
    }

    #[test]
    fn a_picker_owns_every_printable_key_so_its_filter_can_have_them() {
        let keymap = Keymap::default();
        let picker = ContextStack::layered(Layer::Select, false, true, false);
        assert_eq!(
            keymap.lookup(key("q"), &picker),
            None,
            "typing `quit` into a palette must not close it on the first letter"
        );
        assert_eq!(
            keymap.lookup(key("?"), &picker),
            None,
            "and `?` is a filter character here, not the cheatsheet"
        );
        assert_eq!(
            keymap.lookup(key("enter"), &picker),
            Some(Action::OverlayAccept)
        );
        assert_eq!(keymap.lookup(key("down"), &picker), Some(Action::OverlayNext));
        assert_eq!(keymap.lookup(key("up"), &picker), Some(Action::OverlayPrev));
        assert_eq!(
            keymap.lookup(key("esc"), &picker),
            Some(Action::Escape),
            "esc is the one way out, and it is the ladder's first rung"
        );
        // The cheatsheet is the other overlay, and it keeps `q`.
        let sheet = ContextStack::layered(Layer::Overlay, false, true, false);
        assert_eq!(keymap.lookup(key("q"), &sheet), Some(Action::OverlayDismiss));
        assert_eq!(keymap.lookup(key("enter"), &sheet), None);
    }

    #[test]
    fn hints_are_ordered_by_priority_and_never_name_a_shadowed_key() {
        let keymap = Keymap::default();
        let streaming = ContextStack::build(false, false, false, true);
        let hints = keymap.hints(&streaming);
        let priorities: Vec<_> = hints.iter().map(|hint| hint.priority).collect();
        let mut sorted = priorities.clone();
        sorted.sort_unstable_by(|a, b| b.cmp(a));
        assert_eq!(priorities, sorted);
        assert!(hints.iter().any(|hint| hint.action == Action::Steer));

        let completing = ContextStack::build(false, true, false, false);
        let hints = keymap.hints(&completing);
        assert!(
            !hints.iter().any(|hint| hint.action == Action::ExpandLastTool),
            "Tab belongs to the popup here, so the hint bar must not offer it"
        );
    }

    #[test]
    fn every_cheatsheet_row_names_a_key_that_dispatches() {
        let keymap = Keymap::default();
        for (context, entries) in keymap.cheatsheet() {
            for entry in entries {
                let first = entry.keys.split(" / ").next().unwrap().to_owned();
                let parsed = spec::parse_key(&first)
                    .unwrap_or_else(|_| panic!("{} prints unparseable {first:?}", entry.action.id()));
                let stack = ContextStack(vec![context]);
                assert_eq!(
                    keymap.lookup(parsed, &stack),
                    Some(entry.action),
                    "{} in {}",
                    entry.action.id(),
                    context.title()
                );
            }
        }
    }

    #[test]
    fn the_palette_covers_every_declared_action() {
        let keymap = Keymap::default();
        assert_eq!(keymap.palette().len(), BINDINGS.len());
    }

    #[test]
    fn shift_enter_is_a_distinct_binding_from_enter() {
        let keymap = Keymap::default();
        let stack = ContextStack::build(false, false, false, false);
        assert_eq!(keymap.lookup(KeyEvent::new(KeyCode::Enter), &stack), Some(Action::Submit));
        assert_eq!(
            keymap.lookup(KeyEvent::with(KeyCode::Enter, KeyMods::SHIFT), &stack),
            Some(Action::Newline)
        );
    }
}
