import { afterEach, describe, expect, test } from "bun:test";
import { mkdirSync, mkdtempSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { generatedReason, globRegex, ignoreRules, isIgnored, readIndexable, walkRepository } from "../src/index.ts";

const roots: string[] = [];

function repository(files: Record<string, string>): string {
  const root = mkdtempSync(join(tmpdir(), "lyra-map-walk-"));
  roots.push(root);
  for (const [path, content] of Object.entries(files)) {
    const absolute = join(root, path);
    mkdirSync(dirname(absolute), { recursive: true });
    writeFileSync(absolute, content);
  }
  return root;
}

afterEach(() => {
  for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true });
});

describe("ignore semantics", () => {
  test("globs compile the way git reads them", () => {
    expect(globRegex("*.gen.ts").test("schema.gen.ts")).toBe(true);
    expect(globRegex("*.gen.ts").test("a/schema.gen.ts")).toBe(false);
    expect(globRegex("**/build").test("a/b/build")).toBe(true);
    expect(globRegex("src/*.ts").test("src/a.ts")).toBe(true);
    expect(globRegex("src/*.ts").test("src/deep/a.ts")).toBe(false);
    expect(globRegex("{a,b}.ts").test("b.ts")).toBe(true);
    expect(() => globRegex("[unclosed")).toThrow(/opening \[/);
    expect(() => globRegex("{only}")).toThrow(/brace alternatives/);
  });

  test("the last matching rule wins, and negation re-admits", async () => {
    const root = repository({ ".gitignore": "build/\n*.log\n!keep.log\n" });
    const rules = await ignoreRules(root);
    expect(isIgnored("build/out.ts", rules)).toBe(true);
    expect(isIgnored("a/b.log", rules)).toBe(true);
    expect(isIgnored("a/keep.log", rules)).toBe(false);
    expect(isIgnored("src/a.ts", rules)).toBe(false);
  });

  test("Lyra state and dependency trees are excluded whatever .gitignore says", () => {
    for (const path of [".lyra/map.db", "a/.lyra/x.ts", "node_modules/x/index.ts", "target/debug/a.rs", ".git/config", "dist/a.js"]) {
      expect(isIgnored(path, [])).toBe(true);
    }
    expect(isIgnored("src/distance.ts", [])).toBe(false);
  });
});

describe("walking", () => {
  test("collect source files and workspace packages, deterministically", async () => {
    const root = repository({
      "package.json": JSON.stringify({ name: "root" }),
      "packages/core/package.json": JSON.stringify({ name: "@demo/core" }),
      "packages/core/src/b.ts": "export const b = 1;\n",
      "packages/core/src/a.ts": "export const a = 1;\n",
      "packages/core/README.md": "# no",
      "packages/core/data.json": "{}",
      "node_modules/dep/index.ts": "export const d = 1;\n",
    });
    const walk = await walkRepository(root);
    expect(walk.files).toEqual(["packages/core/src/a.ts", "packages/core/src/b.ts"]);
    expect([...walk.packages].sort()).toEqual([
      ["@demo/core", "packages/core"],
      ["root", ""],
    ]);
  });

  test("symlinks are never followed out of the repository", async () => {
    const root = repository({ "src/a.ts": "export const a = 1;\n" });
    const outside = repository({ "escape.ts": "export const escaped = 1;\n" });
    symlinkSync(outside, join(root, "src", "link"));
    expect((await walkRepository(root)).files).toEqual(["src/a.ts"]);
  });
});

describe("file guards", () => {
  test("generated and minified files are detected by content, not by name", () => {
    expect(generatedReason("a/b.ts", "// Code generated by protoc. DO NOT EDIT.\nexport const a = 1;\n")).toBe("generated");
    expect(generatedReason("a/b.ts", "/* @generated */\nexport const a = 1;\n")).toBe("generated");
    expect(generatedReason("a/b.min.js", "var a=1;\n")).toBe("minified");
    expect(generatedReason("a/b.ts", `export const wide = "${"x".repeat(6000)}";\n`)).toBe("minified");
    expect(generatedReason("a/b.ts", "export const a = 1;\n")).toBeUndefined();
    // A marker far below the header is prose, not a claim about the file.
    expect(generatedReason("a/b.ts", `${"// filler\n".repeat(20)}// @generated\n`)).toBeUndefined();
  });

  test("oversized, binary, missing, and unsupported files are refused with a reason", async () => {
    const root = repository({
      "src/ok.ts": "export const a = 1;\n",
      "src/big.ts": `export const big = "${"y".repeat(4000)}";\n`,
      "docs/readme.md": "# hi",
    });
    writeFileSync(join(root, "src", "binary.ts"), Buffer.from([0x65, 0x00, 0x66]));

    expect(await readIndexable(root, "src/ok.ts")).toMatchObject({ ok: true, content: "export const a = 1;\n" });
    expect(await readIndexable(root, "src/big.ts", 100)).toEqual({ ok: false, reason: "too_large" });
    expect(await readIndexable(root, "src/binary.ts")).toEqual({ ok: false, reason: "binary" });
    expect(await readIndexable(root, "src/absent.ts")).toEqual({ ok: false, reason: "missing" });
    expect(await readIndexable(root, "docs/readme.md")).toEqual({ ok: false, reason: "unsupported" });
    expect(await readIndexable(root, "src")).toEqual({ ok: false, reason: "unsupported" });
  });
});
